### ISSUE TITLE
TypeError: 'type' object is not subscriptable in math3d/transform.py

### ISSUE THREAD

**Issue by CLi-11** [LaurentBimont/URX-examples#2]
Hi,

When I run python simple.py, the following error appears

Traceback (most recent call last):
  File "simple.py", line 2, in <module>
    import urx
  File "/usr/local/lib/python3.8/dist-packages/urx/__init__.py", line 4, in <module>
    from urx.urrobot import RobotException, URRobot  # noqa
  File "/usr/local/lib/python3.8/dist-packages/urx/urrobot.py", line 9, in <module>
    from urx import urrtmon
  File "/usr/local/lib/python3.8/dist-packages/urx/urrtmon.py", line 16, in <module>
    import math3d as m3d
  File "/usr/local/lib/python3.8/dist-packages/math3d/__init__.py", line 21, in <module>
    from .transform import Transform, PoseVector
  File "/usr/local/lib/python3.8/dist-packages/math3d/transform.py", line 156, in <module>
    class Transform(object):
  File "/usr/local/lib/python3.8/dist-packages/math3d/transform.py", line 528, in Transform
    ApTs: typing.Union[np.ndarray, tuple[PositionVector]],
TypeError: 'type' object is not subscriptable

How to solve this problem?

**Comment by gqliu-scu** [comment]
Did u have solved this issue？

**Comment by ChenWEIx2** [comment]
use python 3.9
